In [1]:
import pandas as pd
import os

In [2]:
columbia_brood = pd.read_csv(r'C:\Users\MuriloFarias\Desktop\NNS-JULIA\original_data\1Columbia_Brood_Table.csv')

In [3]:
columbia_brood.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43 non-null     int64
 1   System          43 non-null     object
 2   River           43 non-null     object
 3   BroodYear       43 non-null     int64
 4   Total_Recruits  33 non-null     float64
 5   AgeClass_0.1    40 non-null     float64
 6   AgeClass_0.2    40 non-null     float64
 7   AgeClass_0.3    40 non-null     float64
 8   AgeClass_0.4    40 non-null     float64
 9   AgeClass_0.5    39 non-null     float64
 10  AgeClass_1.1    40 non-null     float64
 11  AgeClass_1.2    40 non-null     float64
 12  AgeClass_1.3    40 non-null     float64
 13  AgeClass_1.4    39 non-null     float64
 14  AgeClass_1.5    38 non-null     float64
 15  AgeClass_2.1    40 non-null     float64
 16  AgeClass_2.2    40 non-null     float64
 17  AgeClass_2.3    39 non-null     float64
 18  AgeClass_2.4    38 non-null     float64
 19  AgeClass_3.1    40 non-null     float64
 20  AgeClass_3.2    39 non-null     float64
 21  AgeClass_3.3    38 non-null     float64
 22  AgeClass_3.4    37 non-null     float64
dtypes: float64(19), int64(2), object(2)
memory usage: 7.9+ KB

In [4]:
columbia_brood

,Unnamed: 0,System,River,BroodYear,Total_Recruits,AgeClass_0.1,AgeClass_0.2,AgeClass_0.3,AgeClass_0.4,AgeClass_0.5,...,AgeClass_1.4,AgeClass_1.5,AgeClass_2.1,AgeClass_2.2,AgeClass_2.3,AgeClass_2.4,AgeClass_3.1,AgeClass_3.2,AgeClass_3.3,AgeClass_3.4
0,1,Columbia River,Bonneville Lock & Dam,1980,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,NaN,12143.0,158.0,0.0,0.0,0.0,0.0,0.0
1,2,Columbia River,Bonneville Lock & Dam,1981,NaN,NaN,NaN,0.0,0.0,0.0,...,0.0,0.0,585.0,2371.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Columbia River,Bonneville Lock & Dam,1982,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,510.0,12805.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Columbia River,Bonneville Lock & Dam,1983,121493.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1673.0,5384.0,210.0,0.0,0.0,0.0,0.0,0.0
4,5,Columbia River,Bonneville Lock & Dam,1984,90540.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2057.0,3052.0,157.0,0.0,0.0,0.0,0.0,0.0
5,6,Columbia River,Bonneville Lock & Dam,1985,47821.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,523.0,7681.0,76.0,0.0,0.0,0.0,0.0,0.0
6,7,Columbia River,Bonneville Lock & Dam,1986,43800.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,393.0,342.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8,Columbia River,Bonneville Lock & Dam,1987,87441.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1958.0,15129.0,984.0,0.0,0.0,0.0,0.0,0.0
8,9,Columbia River,Bonneville Lock & Dam,1988,76799.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2894.0,5640.0,106.0,0.0,0.0,0.0,0.0,0.0
9,10,Columbia River,Bonneville Lock & Dam,1989,80861.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1503.0,95.0,0.0,0.0,0.0,0.0,0.0
10,11,Columbia River,Bonneville Lock & Dam,1990,2607.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,146.0,259.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12,Columbia River,Bonneville Lock & Dam,1991,9610.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,764.0,2110.0,341.0,0.0,0.0,0.0,0.0,0.0
12,13,Columbia River,Bonneville Lock & Dam,1992,33691.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,232.0,2343.0,70.0,0.0,0.0,0.0,0.0,0.0
13,14,Columbia River,Bonneville Lock & Dam,1993,50984.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,298.0,1158.0,130.0,0.0,0.0,0.0,0.0,0.0
14,15,Columbia River,Bonneville Lock & Dam,1994,3319.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,194.0,760.0,118.0,0.0,0.0,0.0,0.0,0.0
15,16,Columbia River,Bonneville Lock & Dam,1995,18830.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,466.0,424.0,0.0,0.0,0.0,0.0,0.0,0.0
16,17,Columbia River,Bonneville Lock & Dam,1996,113163.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,427.0,8810.0,508.0,0.0,0.0,1425.0,35.0,0.0
17,18,Columbia River,Bonneville Lock & Dam,1997,124912.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,513.0,20446.0,343.0,0.0,46.0,806.0,0.0,0.0
18,19,Columbia River,Bonneville Lock & Dam,1998,32802.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,116.0,492.0,235.0,0.0,5230.0,0.0,0.0,0.0
19,20,Columbia River,Bonneville Lock & Dam,1999,16813.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2373.0,784.0,0.0,0.0,235.0,267.0,0.0,0.0
20,21,Columbia River,Bonneville Lock & Dam,2000,136515.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,483.0,104.0,0.0,287.0,0.0,0.0,0.0
21,22,Columbia River,Bonneville Lock & Dam,2001,80051.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,783.0,5359.0,610.0,0.0,515.0,0.0,0.0,0.0
22,23,Columbia River,Bonneville Lock & Dam,2002,30479.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,734.0,2660.0,278.0,0.0,0.0,0.0,0.0,0.0
23,24,Columbia River,Bonneville Lock & Dam,2003,16645.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1482.0,6530.0,126.0,0.0,0.0,0.0,0.0,0.0
24,25,Columbia River,Bonneville Lock & Dam,2004,217244.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3687.0,6457.0,0.0,0.0,0.0,0.0,0.0,0.0
25,26,Columbia River,Bonneville Lock & Dam,2005,179140.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1758.0,11156.0,184.0,0.0,0.0,0.0,0.0,0.0
26,27,Columbia River,Bonneville Lock & Dam,2006,405877.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1413.0,7639.0,0.0,0.0,0.0,286.0,0.0,0.0
27,28,Columbia River,Bonneville Lock & Dam,2007,142250.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3721.0,5092.0,0.0,0.0,0.0,0.0,0.0,0.0
28,29,Columbia River,Bonneville Lock & Dam,2008,565794.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2475.0,11190.0,0.0,0.0,0.0,0.0,0.0,0.0
29,30,Columbia River,Bonneville Lock & Dam,2009,132065.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,889.0,4419.0,0.0,0.0,0.0,0.0,0.0,0.0
30,31,Columbia River,Bonneville Lock & Dam,2010,580958.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,433.0,2089.0,0.0,0.0,0.0,0.0,0.0,0.0
31,32,Columbia River,Bonneville Lock & Dam,2011,605785.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,869.0,1828.0,0.0,0.0,0.0,0.0,0.0,0.0
32,33,Columbia River,Bonneville Lock & Dam,2012,334999.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,351.0,0.0,0.0,0.0,78.0,0.0,0.0
33,34,Columbia River,Bonneville Lock & Dam,2013,51655.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,629.0,1816.0,41.0,0.0,476.0,0.0,0.0,0.0
34,35,Columbia River,Bonneville Lock & Dam,2014,202564.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2294.0,2896.0,0.0,0.0,41.0,0.0,0.0,0.0
35,36,Columbia River,Bonneville Lock & Dam,2015,26941.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,14092.0,682.0,0.0,0.0,0.0,0.0,0.0,0.0
36,37,Columbia River,Bonneville Lock & Dam,2016,NaN,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,409.0,988.0,0.0,0.0,0.0,0.0,0.0,0.0
37,38,Columbia River,Bonneville Lock & Dam,2017,NaN,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1437.0,2773.0,0.0,0.0,0.0,0.0,0.0,NaN
38,39,Columbia River,Bonneville Lock & Dam,2018,NaN,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,4224.0,13943.0,200.0,NaN,0.0,0.0,NaN,NaN
39,40,Columbia River,Bonneville Lock & Dam,2019,NaN,0.0,0.0,0.0,0.0,NaN,...,NaN,NaN,744.0,9630.0,NaN,NaN,0.0,NaN,NaN,NaN
40,41,Columbia River,Bonneville Lock & Dam,2020,NaN,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,9395.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,Columbia River,Bonneville Lock & Dam,2021,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,Columbia River,Bonneville Lock & Dam,2022,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
columns_to_sum = [
    'AgeClass_0.1', 'AgeClass_0.2', 'AgeClass_0.3', 'AgeClass_0.4', 'AgeClass_0.5',
    'AgeClass_1.1', 'AgeClass_1.2', 'AgeClass_1.3', 'AgeClass_1.4', 'AgeClass_1.5',
    'AgeClass_2.1', 'AgeClass_2.2', 'AgeClass_2.3', 'AgeClass_2.4',
    'AgeClass_3.1', 'AgeClass_3.2', 'AgeClass_3.3', 'AgeClass_3.4'
]

# Sum all values across those columns
total_sum = columbia_brood[columns_to_sum].sum().sum()

print("total_sum age:", total_sum)



Total_Recruits = columbia_brood['Total_Recruits'].sum()

print("Total_Recruits:", Total_Recruits)

total_sum age: 7153541.0
Total_Recruits: 4664448.0

In [6]:
for col in columbia_brood.columns:
    print(col)

Unnamed: 0
System
River
BroodYear
Total_Recruits
AgeClass_0.1
AgeClass_0.2
AgeClass_0.3
AgeClass_0.4
AgeClass_0.5
AgeClass_1.1
AgeClass_1.2
AgeClass_1.3
AgeClass_1.4
AgeClass_1.5
AgeClass_2.1
AgeClass_2.2
AgeClass_2.3
AgeClass_2.4
AgeClass_3.1
AgeClass_3.2
AgeClass_3.3
AgeClass_3.4

In [7]:
print(columbia_brood.columns.tolist())

['Unnamed: 0', 'System', 'River', 'BroodYear', 'Total_Recruits', 'AgeClass_0.1', 'AgeClass_0.2', 'AgeClass_0.3', 'AgeClass_0.4', 'AgeClass_0.5', 'AgeClass_1.1', 'AgeClass_1.2', 'AgeClass_1.3', 'AgeClass_1.4', 'AgeClass_1.5', 'AgeClass_2.1', 'AgeClass_2.2', 'AgeClass_2.3', 'AgeClass_2.4', 'AgeClass_3.1', 'AgeClass_3.2', 'AgeClass_3.3', 'AgeClass_3.4']

In [8]:
columbia_brood = columbia_brood.loc[:, (columbia_brood.notna() & (columbia_brood != 0)).any()]

In [9]:
columbia_brood.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43 non-null     int64
 1   System          43 non-null     object
 2   River           43 non-null     object
 3   BroodYear       43 non-null     int64
 4   Total_Recruits  33 non-null     float64
 5   AgeClass_1.1    40 non-null     float64
 6   AgeClass_1.2    40 non-null     float64
 7   AgeClass_1.3    40 non-null     float64
 8   AgeClass_2.1    40 non-null     float64
 9   AgeClass_2.2    40 non-null     float64
 10  AgeClass_2.3    39 non-null     float64
 11  AgeClass_3.1    40 non-null     float64
 12  AgeClass_3.2    39 non-null     float64
 13  AgeClass_3.3    38 non-null     float64
dtypes: float64(10), int64(2), object(2)
memory usage: 4.8+ KB

In [10]:
columns_to_sum = [
    'AgeClass_1.1', 'AgeClass_1.2', 'AgeClass_1.3',
    'AgeClass_2.1', 'AgeClass_2.2', 'AgeClass_2.3',
    'AgeClass_3.1', 'AgeClass_3.2', 'AgeClass_3.3'
]

# Sum all values across those columns
total_sum = columbia_brood[columns_to_sum].sum().sum()

print("total_sum age:", total_sum)



Total_Recruits = columbia_brood['Total_Recruits'].sum()

print("Total_Recruits:", Total_Recruits)

total_sum age: 7153541.0
Total_Recruits: 4664448.0

In [11]:
columbia_brood

,Unnamed: 0,System,River,BroodYear,Total_Recruits,AgeClass_1.1,AgeClass_1.2,AgeClass_1.3,AgeClass_2.1,AgeClass_2.2,AgeClass_2.3,AgeClass_3.1,AgeClass_3.2,AgeClass_3.3
0,1,Columbia River,Bonneville Lock & Dam,1980,NaN,NaN,NaN,1732.0,NaN,12143.0,158.0,0.0,0.0,0.0
1,2,Columbia River,Bonneville Lock & Dam,1981,NaN,NaN,150419.0,9094.0,585.0,2371.0,0.0,0.0,0.0,0.0
2,3,Columbia River,Bonneville Lock & Dam,1982,NaN,1461.0,21928.0,2611.0,510.0,12805.0,0.0,0.0,0.0,0.0
3,4,Columbia River,Bonneville Lock & Dam,1983,121493.0,24062.0,76905.0,13259.0,1673.0,5384.0,210.0,0.0,0.0,0.0
4,5,Columbia River,Bonneville Lock & Dam,1984,90540.0,22999.0,58466.0,3809.0,2057.0,3052.0,157.0,0.0,0.0,0.0
5,6,Columbia River,Bonneville Lock & Dam,1985,47821.0,547.0,33993.0,5001.0,523.0,7681.0,76.0,0.0,0.0,0.0
6,7,Columbia River,Bonneville Lock & Dam,1986,43800.0,298.0,29089.0,13678.0,393.0,342.0,0.0,0.0,0.0,0.0
7,8,Columbia River,Bonneville Lock & Dam,1987,87441.0,7260.0,56355.0,5755.0,1958.0,15129.0,984.0,0.0,0.0,0.0
8,9,Columbia River,Bonneville Lock & Dam,1988,76799.0,4072.0,56044.0,8043.0,2894.0,5640.0,106.0,0.0,0.0,0.0
9,10,Columbia River,Bonneville Lock & Dam,1989,80861.0,5170.0,65510.0,8583.0,0.0,1503.0,95.0,0.0,0.0,0.0
10,11,Columbia River,Bonneville Lock & Dam,1990,2607.0,0.0,1899.0,303.0,146.0,259.0,0.0,0.0,0.0,0.0
11,12,Columbia River,Bonneville Lock & Dam,1991,9610.0,440.0,4860.0,1095.0,764.0,2110.0,341.0,0.0,0.0,0.0
12,13,Columbia River,Bonneville Lock & Dam,1992,33691.0,2451.0,26262.0,2333.0,232.0,2343.0,70.0,0.0,0.0,0.0
13,14,Columbia River,Bonneville Lock & Dam,1993,50984.0,534.0,41379.0,7485.0,298.0,1158.0,130.0,0.0,0.0,0.0
14,15,Columbia River,Bonneville Lock & Dam,1994,3319.0,315.0,1373.0,559.0,194.0,760.0,118.0,0.0,0.0,0.0
15,16,Columbia River,Bonneville Lock & Dam,1995,18830.0,2939.0,14403.0,598.0,466.0,424.0,0.0,0.0,0.0,0.0
16,17,Columbia River,Bonneville Lock & Dam,1996,113163.0,1558.0,88006.0,12394.0,427.0,8810.0,508.0,0.0,1425.0,35.0
17,18,Columbia River,Bonneville Lock & Dam,1997,124912.0,3825.0,92046.0,6887.0,513.0,20446.0,343.0,46.0,806.0,0.0
18,19,Columbia River,Bonneville Lock & Dam,1998,32802.0,1171.0,19533.0,6025.0,116.0,492.0,235.0,5230.0,0.0,0.0
19,20,Columbia River,Bonneville Lock & Dam,1999,16813.0,458.0,12359.0,337.0,2373.0,784.0,0.0,235.0,267.0,0.0
20,21,Columbia River,Bonneville Lock & Dam,2000,136515.0,9713.0,120481.0,5447.0,0.0,483.0,104.0,287.0,0.0,0.0
21,22,Columbia River,Bonneville Lock & Dam,2001,80051.0,1218.0,64751.0,6815.0,783.0,5359.0,610.0,515.0,0.0,0.0
22,23,Columbia River,Bonneville Lock & Dam,2002,30479.0,804.0,23338.0,2665.0,734.0,2660.0,278.0,0.0,0.0,0.0
23,24,Columbia River,Bonneville Lock & Dam,2003,16645.0,201.0,7226.0,1080.0,1482.0,6530.0,126.0,0.0,0.0,0.0
24,25,Columbia River,Bonneville Lock & Dam,2004,217244.0,9734.0,186773.0,10593.0,3687.0,6457.0,0.0,0.0,0.0,0.0
25,26,Columbia River,Bonneville Lock & Dam,2005,179140.0,15260.0,140752.0,10030.0,1758.0,11156.0,184.0,0.0,0.0,0.0
26,27,Columbia River,Bonneville Lock & Dam,2006,405877.0,18137.0,357747.0,20655.0,1413.0,7639.0,0.0,0.0,286.0,0.0
27,28,Columbia River,Bonneville Lock & Dam,2007,142250.0,6178.0,120868.0,6391.0,3721.0,5092.0,0.0,0.0,0.0,0.0
28,29,Columbia River,Bonneville Lock & Dam,2008,565794.0,32729.0,494616.0,24784.0,2475.0,11190.0,0.0,0.0,0.0,0.0
29,30,Columbia River,Bonneville Lock & Dam,2009,132065.0,6637.0,116445.0,3675.0,889.0,4419.0,0.0,0.0,0.0,0.0
30,31,Columbia River,Bonneville Lock & Dam,2010,580958.0,32198.0,518152.0,28086.0,433.0,2089.0,0.0,0.0,0.0,0.0
31,32,Columbia River,Bonneville Lock & Dam,2011,605785.0,87497.0,478970.0,36621.0,869.0,1828.0,0.0,0.0,0.0,0.0
32,33,Columbia River,Bonneville Lock & Dam,2012,334999.0,692.0,301578.0,32300.0,0.0,351.0,0.0,0.0,78.0,0.0
33,34,Columbia River,Bonneville Lock & Dam,2013,51655.0,2471.0,43014.0,3208.0,629.0,1816.0,41.0,476.0,0.0,0.0
34,35,Columbia River,Bonneville Lock & Dam,2014,202564.0,11400.0,185170.0,763.0,2294.0,2896.0,0.0,41.0,0.0,0.0
35,36,Columbia River,Bonneville Lock & Dam,2015,26941.0,696.0,10880.0,591.0,14092.0,682.0,0.0,0.0,0.0,0.0
36,37,Columbia River,Bonneville Lock & Dam,2016,NaN,34333.0,337115.0,20844.0,409.0,988.0,0.0,0.0,0.0,0.0
37,38,Columbia River,Bonneville Lock & Dam,2017,NaN,2943.0,87103.0,14244.0,1437.0,2773.0,0.0,0.0,0.0,0.0
38,39,Columbia River,Bonneville Lock & Dam,2018,NaN,41393.0,628929.0,33729.0,4224.0,13943.0,200.0,0.0,0.0,NaN
39,40,Columbia River,Bonneville Lock & Dam,2019,NaN,13084.0,249066.0,18575.0,744.0,9630.0,NaN,0.0,NaN,NaN
40,41,Columbia River,Bonneville Lock & Dam,2020,NaN,30066.0,706422.0,NaN,9395.0,NaN,NaN,NaN,NaN,NaN
41,42,Columbia River,Bonneville Lock & Dam,2021,NaN,11687.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,Columbia River,Bonneville Lock & Dam,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
columbia_brood = columbia_brood.fillna(0)

In [13]:
columns_to_sum = [
    'AgeClass_1.1', 'AgeClass_1.2', 'AgeClass_1.3',
    'AgeClass_2.1', 'AgeClass_2.2', 'AgeClass_2.3',
    'AgeClass_3.1', 'AgeClass_3.2', 'AgeClass_3.3'
]

# Sum all values across those columns
total_sum = columbia_brood[columns_to_sum].sum().sum()

print("total_sum age:", total_sum)



Total_Recruits = columbia_brood['Total_Recruits'].sum()

print("Total_Recruits:", Total_Recruits)

total_sum age: 7153541.0
Total_Recruits: 4664448.0

In [14]:
# --- STEP 1: Select relevant age class columns ---
age_class_columns = [col for col in columbia_brood.columns if col.startswith('AgeClass_')]
cols_to_keep = ['BroodYear', 'Total_Recruits'] + age_class_columns
clean_df_columbia_brood = columbia_brood[cols_to_keep].copy()

# --- STEP 2: Melt to long format ---
clean_df_columbia_brood_long = clean_df_columbia_brood.melt(
    id_vars=['BroodYear', 'Total_Recruits'],
    value_vars=age_class_columns,
    var_name='AgeClass',
    value_name='RecruitCount'
)

In [15]:
clean_df_columbia_brood

,BroodYear,Total_Recruits,AgeClass_1.1,AgeClass_1.2,AgeClass_1.3,AgeClass_2.1,AgeClass_2.2,AgeClass_2.3,AgeClass_3.1,AgeClass_3.2,AgeClass_3.3
0,1980,0.0,0.0,0.0,1732.0,0.0,12143.0,158.0,0.0,0.0,0.0
1,1981,0.0,0.0,150419.0,9094.0,585.0,2371.0,0.0,0.0,0.0,0.0
2,1982,0.0,1461.0,21928.0,2611.0,510.0,12805.0,0.0,0.0,0.0,0.0
3,1983,121493.0,24062.0,76905.0,13259.0,1673.0,5384.0,210.0,0.0,0.0,0.0
4,1984,90540.0,22999.0,58466.0,3809.0,2057.0,3052.0,157.0,0.0,0.0,0.0
5,1985,47821.0,547.0,33993.0,5001.0,523.0,7681.0,76.0,0.0,0.0,0.0
6,1986,43800.0,298.0,29089.0,13678.0,393.0,342.0,0.0,0.0,0.0,0.0
7,1987,87441.0,7260.0,56355.0,5755.0,1958.0,15129.0,984.0,0.0,0.0,0.0
8,1988,76799.0,4072.0,56044.0,8043.0,2894.0,5640.0,106.0,0.0,0.0,0.0
9,1989,80861.0,5170.0,65510.0,8583.0,0.0,1503.0,95.0,0.0,0.0,0.0
10,1990,2607.0,0.0,1899.0,303.0,146.0,259.0,0.0,0.0,0.0,0.0
11,1991,9610.0,440.0,4860.0,1095.0,764.0,2110.0,341.0,0.0,0.0,0.0
12,1992,33691.0,2451.0,26262.0,2333.0,232.0,2343.0,70.0,0.0,0.0,0.0
13,1993,50984.0,534.0,41379.0,7485.0,298.0,1158.0,130.0,0.0,0.0,0.0
14,1994,3319.0,315.0,1373.0,559.0,194.0,760.0,118.0,0.0,0.0,0.0
15,1995,18830.0,2939.0,14403.0,598.0,466.0,424.0,0.0,0.0,0.0,0.0
16,1996,113163.0,1558.0,88006.0,12394.0,427.0,8810.0,508.0,0.0,1425.0,35.0
17,1997,124912.0,3825.0,92046.0,6887.0,513.0,20446.0,343.0,46.0,806.0,0.0
18,1998,32802.0,1171.0,19533.0,6025.0,116.0,492.0,235.0,5230.0,0.0,0.0
19,1999,16813.0,458.0,12359.0,337.0,2373.0,784.0,0.0,235.0,267.0,0.0
20,2000,136515.0,9713.0,120481.0,5447.0,0.0,483.0,104.0,287.0,0.0,0.0
21,2001,80051.0,1218.0,64751.0,6815.0,783.0,5359.0,610.0,515.0,0.0,0.0
22,2002,30479.0,804.0,23338.0,2665.0,734.0,2660.0,278.0,0.0,0.0,0.0
23,2003,16645.0,201.0,7226.0,1080.0,1482.0,6530.0,126.0,0.0,0.0,0.0
24,2004,217244.0,9734.0,186773.0,10593.0,3687.0,6457.0,0.0,0.0,0.0,0.0
25,2005,179140.0,15260.0,140752.0,10030.0,1758.0,11156.0,184.0,0.0,0.0,0.0
26,2006,405877.0,18137.0,357747.0,20655.0,1413.0,7639.0,0.0,0.0,286.0,0.0
27,2007,142250.0,6178.0,120868.0,6391.0,3721.0,5092.0,0.0,0.0,0.0,0.0
28,2008,565794.0,32729.0,494616.0,24784.0,2475.0,11190.0,0.0,0.0,0.0,0.0
29,2009,132065.0,6637.0,116445.0,3675.0,889.0,4419.0,0.0,0.0,0.0,0.0
30,2010,580958.0,32198.0,518152.0,28086.0,433.0,2089.0,0.0,0.0,0.0,0.0
31,2011,605785.0,87497.0,478970.0,36621.0,869.0,1828.0,0.0,0.0,0.0,0.0
32,2012,334999.0,692.0,301578.0,32300.0,0.0,351.0,0.0,0.0,78.0,0.0
33,2013,51655.0,2471.0,43014.0,3208.0,629.0,1816.0,41.0,476.0,0.0,0.0
34,2014,202564.0,11400.0,185170.0,763.0,2294.0,2896.0,0.0,41.0,0.0,0.0
35,2015,26941.0,696.0,10880.0,591.0,14092.0,682.0,0.0,0.0,0.0,0.0
36,2016,0.0,34333.0,337115.0,20844.0,409.0,988.0,0.0,0.0,0.0,0.0
37,2017,0.0,2943.0,87103.0,14244.0,1437.0,2773.0,0.0,0.0,0.0,0.0
38,2018,0.0,41393.0,628929.0,33729.0,4224.0,13943.0,200.0,0.0,0.0,0.0
39,2019,0.0,13084.0,249066.0,18575.0,744.0,9630.0,0.0,0.0,0.0,0.0
40,2020,0.0,30066.0,706422.0,0.0,9395.0,0.0,0.0,0.0,0.0,0.0
41,2021,0.0,11687.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,2022,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
# STEP 1: Keep only relevant columns
age_class_columns = [col for col in clean_df_columbia_brood.columns if col.startswith('AgeClass_')]
cols_to_keep = ['BroodYear', 'Total_Recruits'] + age_class_columns
clean_df_columbia_return = clean_df_columbia_brood[cols_to_keep].copy()


# STEP 3: Remove age class columns where all values are 0
age_class_columns = [col for col in age_class_columns if clean_df_columbia_return[col].sum() > 0]

# STEP 4: Melt to long format
clean_df_columbia_return_long = clean_df_columbia_return.melt(
    id_vars=['BroodYear'],
    value_vars=age_class_columns,
    var_name='AgeClass',
    value_name='Total_age'
)

In [21]:
clean_df_columbia_return_long

     BroodYear      AgeClass  Total_age
0         1980  AgeClass_1.1        0.0
1         1981  AgeClass_1.1        0.0
2         1982  AgeClass_1.1     1461.0
3         1983  AgeClass_1.1    24062.0
4         1984  AgeClass_1.1    22999.0
..         ...           ...        ...
382       2018  AgeClass_3.3        0.0
383       2019  AgeClass_3.3        0.0
384       2020  AgeClass_3.3        0.0
385       2021  AgeClass_3.3        0.0
386       2022  AgeClass_3.3        0.0

[387 rows x 3 columns]

In [22]:
Total_ReturnCount = clean_df_columbia_return_long['Total_age'].sum()
print("Total ReturnCount across all years:", Total_ReturnCount)

Total ReturnCount across all years: 7153541.0

In [23]:
columns_to_sum = [
    'AgeClass_1.1', 'AgeClass_1.2', 'AgeClass_1.3',
    'AgeClass_2.1', 'AgeClass_2.2', 'AgeClass_2.3',
    'AgeClass_3.1', 'AgeClass_3.2', 'AgeClass_3.3'
]

# Sum all values across those columns
total_sum = clean_df_columbia_brood[columns_to_sum].sum().sum()

print("total_sum age:", total_sum)



Total_Recruits = clean_df_columbia_brood['Total_Recruits'].sum()

print("Total_Recruits:", Total_Recruits)

total_sum age: 7153541.0
Total_Recruits: 4664448.0

In [24]:
clean_df_columbia_brood = clean_df_columbia_brood[['BroodYear', 'Total_Recruits']]
clean_df_columbia_brood = clean_df_columbia_brood[clean_df_columbia_brood['Total_Recruits'] != 0]

In [25]:

Total_Recruits = clean_df_columbia_brood['Total_Recruits'].sum()

print("Total_Recruits:", Total_Recruits)

Total_Recruits: 4664448.0

In [26]:
broodyear_counts = clean_df_columbia_brood['BroodYear'].value_counts()
more_than_one = broodyear_counts[broodyear_counts > 0]

print(more_than_one.sort_index())

BroodYear
1983    1
1984    1
1985    1
1986    1
1987    1
1988    1
1989    1
1990    1
1991    1
1992    1
1993    1
1994    1
1995    1
1996    1
1997    1
1998    1
1999    1
2000    1
2001    1
2002    1
2003    1
2004    1
2005    1
2006    1
2007    1
2008    1
2009    1
2010    1
2011    1
2012    1
2013    1
2014    1
2015    1
Name: count, dtype: int64

In [27]:
Total_Recruits = clean_df_columbia_brood['Total_Recruits'].sum()

print("Total_Recruits:", Total_Recruits)

Total_Recruits: 4664448.0

In [28]:
clean_df_columbia_brood

    BroodYear  Total_Recruits
3        1983        121493.0
4        1984         90540.0
5        1985         47821.0
6        1986         43800.0
7        1987         87441.0
8        1988         76799.0
9        1989         80861.0
10       1990          2607.0
11       1991          9610.0
12       1992         33691.0
13       1993         50984.0
14       1994          3319.0
15       1995         18830.0
16       1996        113163.0
17       1997        124912.0
18       1998         32802.0
19       1999         16813.0
20       2000        136515.0
21       2001         80051.0
22       2002         30479.0
23       2003         16645.0
24       2004        217244.0
25       2005        179140.0
26       2006        405877.0
27       2007        142250.0
28       2008        565794.0
29       2009        132065.0
30       2010        580958.0
31       2011        605785.0
32       2012        334999.0
33       2013         51655.0
34       2014        202564.0
35       2015         26941.0

In [ ]:
clean_df_columbia_brood.to_csv('Cleaned_1Columbia_Brood.csv', index=False)